# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: docker build . -t dynamicd/jenksinci:v1
    displayName: 'Run docker build'
