# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables: 
  dockerrepo: dynamicd/winjenkins
  majorMinorVersion: 1.0
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

stages:
  - stage: gatherCurrentBuildInfo
    jobs:
      - job: GatherCurrentReleases
        pool:
          vmImage: 'windows-2019'
        steps:
          - task: PowerShell@2
            displayName: Get Latest Version of NanoServer
            inputs:
              script: .\scripts\getnanoversion.ps1
  - stage: buildAndPush
    jobs:
      - job: DockerBuild
        pool:
          vmImage: 'windows-2019'
        steps:
          - task: Docker@2
            displayName: Login to Docker Hub
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            inputs:
              command: login
              containerRegistry: DockerHub
          - task: Docker@2
            displayName: Build
            condition: succeeded()
            inputs:
              command: build
              arguments: --build-arg VERSIONNANO=$(versionNano)
              repository: $(dockerrepo)
              tags: v$(majorMinorVersion).$(semanticVersion)
          - task: Docker@2
            displayName: Push
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            inputs:
              command: push
              repository: $(dockerrepo)
              tags: |
                latest
                $(versionNano)
