#Target Nano Container
#----------------------
FROM mcr.microsoft.com/windows/nanoserver:1809

# copy files from the builder
ADD http://mirrors.jenkins.io/war-stable/latest/jenkins.war C:/jenkins/jenkins.war
ADD http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185 C:/install/jre.exe

#Install Java
RUN C:\install\jre.exe /s INSTALLDIR=c:\Java\jre1.8.0_91 /L install64.log

#cleanup
RUN powershell -command rm -Recurse C:\install -Force

#run jenkins
CMD ["java","-jar","c:\\jenkins\\jenkins.war"]

# LABEL must be last for proper base image discoverability
LABEL maintainer="justin.dynamicd@gmail.com"
LABEL description="Jenkinsci for Windows"